### ISSUE TITLE
Update of Reinheit Theme

### ISSUE THREAD

**Issue by stef204** [Lootyhoof/reinheit#1]
~~been using your reinheit theme with palemoon for over 1 year.
recently, have noticed problems with palemoon where website dialog boxes, menu items and bookmarks folder will just not drop down or open, no matter what I do.
please see [here](https://forum.palemoon.org/viewtopic.php?f=37&t=11875l).
palemoon underwent some important changes with version 26 and I am wondering if any of these changes might have required some adjustments in reinheit.  the timing would seem to coincide with the problems described above.  I have switched back to default theme and so far have not encountered these problems.  any chance you might take a look or test it on your side?~~

edit: the bug i refer to also happens with the default theme so seems to be unrelated to reinheit. please close this issue, apologies.

**Comment by Lootyhoof** [comment]
Good to know, thank you for the update!
